package com.shieldlm.detection;

public enum RiskSignal {
    OVERRIDE_INTENT,
    PROMPT_LEAK_INTENT,
    SECRET_EXTRACTION_INTENT,
    UNSAFE_CONTENT_INTENT,
    ROLE_HIJACK_INTENT,
    VIOLENT_CRIME_INTENT,
    DRUG_CRIME_INTENT,
    WEAPON_EXPLOSIVE_INTENT,
    CYBER_CRIME_INTENT,
    FRAUD_THEFT_INTENT,
    OUTPUT_FORMAT_PROBE
}
